[tool.poetry]
name = "src"
version = "0.1.0"
description = "Bloom scrapping application"
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
apscheduler = "3.9.1"
autopep8 = "1.5.4"
pandas = "1.4.4"
selenium = "4.6.0"
undetected-chromedriver = "3.4.6"
openpyxl = "^3.1.0"
pydantic = "1.10.4"
pyyaml = "6.0"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.0.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
