[tool.poetry]
name = "bloom"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
apscheduler = "3.9.1"
autopep8 = "1.5.4"
pandas = "1.4.4"
selenium = "4.6.0"
undetected-chromedriver = "3.1.6"
openpyxl = "^3.1.0"
pyyaml = "6.0"
pre-commit = "^3.0.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
