version: "3"
services:
  scrapper:
    container_name: bloom_scraper
    build:
      context: ../
      dockerfile: ./docker-env/Dockerfile
      platforms:
        - "linux/amd64"
    image: bloom_scraper
    volumes:
      - type: volume
        source: persistentdata
        target: /data
      - type: bind
        source: ..
        target: /source_code/

volumes:
  persistentdata:
