version: "3"
services:
  scrapper:
    container_name: bloom_scraper
    build:
      context: ../
      dockerfile: ./docker-env/Dockerfile
    platform: "linux/amd64"
    image: bloom_scraper
    #entrypoint: ["poetry","run","python3", "app.py"]
    volumes:
      - type: bind
        source: ..
        target: /source_code/